name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - master  # Set this to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.3  # Specify the Ruby version you need

    - name: Build and deploy
      uses: helaili/jekyll-action@2.0.4
      env:
        JEKYLL_PAT: ${{ secrets.GITHUB_TOKEN }}
